### PR TITLE
Updated screenshots!

### PR DESCRIPTION
**Pull request by TheGamer1002**
Let me know if you'd like screenshots of another specific thing, like widgets.

### CODE REVIEW

**Comment by papjul** [comment]
Your screenshots make me realize there are contrasts in some places 😅

Thank you so much, there are many screenshots, I will cherry-pick (settings will be redesigned so I will skip for now 😉)

**Comment by TheGamer1002** [comment]
I added 2 in locations where the background is what you described in my previous PR!

**Comment by TheGamer1002** [comment]
I might be able to help out with some programming later today, so let me know if there's anything I can help with!

**Comment by papjul** [comment]
> I might be able to help out with some programming later today, so let me know if there's anything I can help with!

Oh, that would be really great! When you will be ready, could you join our [Matrix room](https://matrix.to/#/#breezy-weather:matrix.org) so we can discuss about it? Thanks!

**Comment by papjul** [comment]
Cherry-picked

**Pull request closed without merging**
