### PR TITLE
Gadgetbridge: WeatherSpec v4

### PR DESCRIPTION
**Pull request by joserebelo**
Introduce support for new WeatherSpec v4 fields.

WIP PR on Gadgetbridge: https://codeberg.org/Freeyourgadget/Gadgetbridge/pulls/3273

### CODE REVIEW

**Comment by papjul** [comment]
Will this still work with users of a GadgetBridge containing previous version of WeatherSpec?

We do have an air quality index, however there are many scales (US AQI, Chinese MET, EU AQI, Plume AQI). In Breezy Weather, we use Plume because it's universal, easy to calculate and based on WMO thresholds.

**Comment by joserebelo** [comment]
> Will this still work with users of a GadgetBridge containing previous version of WeatherSpec?

Yup, old versions only read the fields they know, and we didn't rename any, so it's backwards compatible.

> We do have an air quality index, however there are many scales (US AQI, Chinese MET, EU AQI, Plume AQI). In Breezy Weather, we use Plume because it's universal, easy to calculate and based on WMO thresholds.

This is a good callout, thanks. I am actually not sure what scale the devices expect at this point - my device requests it, but currently has no way of displaying it.

I'll document that the WeatherSpec expects Plume AQI, and assume we can convert to other scales if needed.

**Comment by papjul** [comment]
> I'll document that the WeatherSpec expects Plume AQI, and assume we can convert to other scales if needed.

It's not possible to convert between scales. Plume AQI uses 1-hour mean to calculate it, so you could theorically calculate it yourself.

However, other national scales use 1-hour, 8-hour mean or 24-hour mean for each pollutant (and then take the highest index from each pollutant index). See here: https://en.m.wikipedia.org/wiki/Air_quality_index

**Comment by joserebelo** [comment]
Ah, wait, I misunderstood. Right now, I'm only sending the pollutant concentrations, which are raw values, not the AQI.

I need to try and understand what AQI the devices expect, but it might be reasonable to explicitly name it aqiPlume or something then on the GB side. I'll check this out.

**Comment by joserebelo** [comment]
@randomshell thank you, that's good insight - so Zepp OS does expect Plume AQI :)

**Comment by papjul** [comment]
This may also be a coincidence.

Plume AQI is the scale used by AccuWeather (they bought the company), and it was revised a few months ago to take new WMO thresholds revised in 2021. So you may have two Plume scales in the wild.

**Comment by papjul** [comment]
> For instance PM2.5 is ~14.7 in Breezy and ~47 in Zepp.

You forgot units.

14.7 μg / m³ translates to AQI 47 (or something like that, since 15 μg / m³ translates to AQI 50).

**Comment by joserebelo** [comment]
It does look like Zepp OS devices expect the AQI for each pollutant, and then `"aqi"` just contains the max from across all.

From a WeatherSpec perspective, I think it makes sense to send the raw concentrations, but we could also send the raw AQI for each.

**Comment by joserebelo** [comment]
The /alerts endpoint that the watches call, to fetch weather alerts.

But nevermind, discussions on the Zepp API are out of scope for this PR :)

**Comment by papjul** [comment]
Please let me know once it is merged upstream ;)

**Comment by joserebelo** [comment]
@papjul a suggestion was made on the Gadgetbridge PR that I think makes sense, but I'm not sure how to best implement it on Breezy Weather.

I have added a `validity` field to the weatherspec, which would allow devices to know how long the weather prediction is valid and cache it accordingly (matching the update period of the weather source).

Since in Breezy Weather weather can come from multiple sources, I'm thinking it would make sense to use the minimum across all weather sources that were used.

We have the list of weather sources in the `Location` class, but I think that each weather source should declare its own validity, to avoid maintaining that on the `GadgetBridgeService`. However, it's not clear to me how I can get the weather source from the sourceId.

Could I get your thoughts on this?

**Comment by papjul** [comment]
> I have added a `validity` field to the weatherspec, which would allow devices to know how long the weather prediction is valid and cache it accordingly (matching the update period of the weather source).

I only know MET Norway which send a validity header, but it’s handled by OKHttp on its own.

I’m unsure what is the purpose of that `validity` from Gadgetbridge side, what would be cached there, as we push it from Breezy Weather? Breezy Weather only sends it on background update job or on force refresh. If user forces refresh, they expects their gadget to be updated at the same time.

**Comment by joserebelo** [comment]
My understanding is that on devices with limited resources, it's useful to know how often the weather source updates it, so that the device only keeps the information for that long (see the full discussion in the [Gadgetbridge PR](https://codeberg.org/Freeyourgadget/Gadgetbridge/pulls/3273#issuecomment-1071430)).

I am fine with not doing this change for now, as I am also lacking enough context on such devices.

**Comment by papjul** [comment]
In that case, the device should erase everything that is in the past at regular intervals, and once the last day of daily forecast is over, there is nothing left anymore to keep.

But is really this kind of data taking that much space? I'm not sending images or videos, just text…

**Comment by joserebelo** [comment]
We're talking about devices with 64KB of ram ;)

I was searching and asking around, since I also don't have full context / visibility on how all devices supported by Gadgetbridge work. From what I can gather, due to the way they keep and display weather information, multiple weather updates can be kept in memory up to some expiry period, which should more or less match the update period of the weather provider.

I also think it would be useful to provide the refresh period of the app itself , so that we can expire weather from the Gadgetbridge's own cache (this would be useful for some other integrations I'm working on with other devices). From what I can see, it should be as simple as sending `SettingsManager.getInstance(this).updateInterval`.

If you think providing the update period for each source is too cumbersome, I think we could work with the app update period. I still think I will probably add both to the WeatherSpec.

**Comment by papjul** [comment]
> From what I can see, it should be as simple as sending `SettingsManager.getInstance(this).updateInterval`.

Update interval is not a reliable info at all. It's the periodic time we ask Android to execute our job, but:
- Android does not guarantee it will honor that period. We have a 10 min backoff policy so that it can execute it at the time it thinks is the best (before or after).
- Some non-standard Android devices may have their own backoff policy or aggressive killing of background jobs.
- It does not execute when there is no network. For example, you turn off wifi at night, and it won't be executed at all.
- User can decide to not have background jobs when battery is low.
- Update interval can be "never".

By default, refresh rate is 1 hours 30 min, so if 1 h 31 later it's not yet refreshed, you will delete all weather data from gadget? That doesn't make any sense to me, the data is still valid 1 h 31 later, especially the daily forecast ;)

Looking at the PR, I may be wrong but I seem to understand that the gadget is actually expecting a start time and end time (what you call validity) for each hourly and daily, which would make much more sense to me, so that the gadget can safely delete old forecast one by one when timestamp of end time is over. It just expects the end time because it's too lazy/hasn't enough memory to calculate it by themself, but that's something Gadgetbridge can easily take care off, and it would be retroactively compatible with older weather spec versions at the same time.

**Comment by joserebelo** [comment]
@papjul I don't expect it to be accurate to the second, just an estimate :)

That said, you raise some very good points, and I do believe this needs further discussion on the Gadgetbridge side - I have removed the refresh periods from the WeatherSpec.

The PR has been landed in Gadgetbridge, and this one should now be ready for review.

@StevenAlexander44 fyi, this includes a feels like temperature.

**Comment by StevenAlexander44** [comment]
> @StevenAlexander44 fyi, this includes a feels like temperature.

Very cool! Thank you :)

**Comment by papjul** [comment]
Is there a way to access old nightly builds so I can test sending v4 still works on old app versions not supporting v4?

Or do I need to build https://codeberg.org/Freeyourgadget/Gadgetbridge/commit/b7e6a39ec1f0aeedc9228501d1fe0de5f3416708 manually? If so, anything I should know?

Is a stable version expected soon? It would be easier to switch between builds for me.

**Comment by joserebelo** [comment]
Old nightly builds are not available, unfortunately. There is nothing special about building Gadgetbridge that I can remember.
v4 should work on old app versions without issues, as the [GenericWeatherReceiver](https://codeberg.org/Freeyourgadget/Gadgetbridge/src/branch/master/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/externalevents/GenericWeatherReceiver.java) simply gets the fields it knows about from the json object. New fields will be simply ignored.

**Comment by papjul** [comment]
Just to be sure because daily had a different behavior, but you expect all hourlys we have?
I have a handy "next24Hours" (starting from current hour) that we can use.
Usually, all sources provide 24 hours of hourly forecast with a 1 hour granularity, but some may go up to 16 days of hourly forecast. Some may switch to 3-hour timespan or 6-hour after a few days.

**Comment by joserebelo** [comment]
The number of hourly values support varies by device. From the few samples I saw, Zepp OS devices request up to the next 72h, starting from the current hour. I am currently discarding values before the current hour before sending them to the device, and only sending up to the requested timestamp.

16 days does seem excessive, but I am not sure what should be the lower bound- or even if it's that impactful to just send everything.

**Comment by Orhideous** [comment]
Tested this feature (actually, `weatherspec-multiple` branch) on Amazfit GTS4, works as intended.
image

But for some reason UV index on watch not displayed, despite being present in cached weather data.
image
image
F/W: 3.18.1.1

**Comment by joserebelo** [comment]
@Orhideous thanks for testing (that branch is still a work in progress :p for once this one is merged).

Yes - Zepp OS is still failing to receive some of the values, but that's a device-specific problem, I still haven't figured out what is not being sent correctly to the watch.

From a WeatherSpec perspective, I believe Gadgetbridge is receiving the data correctly, as you mention.

**Comment by papjul** [comment]
> I am currently discarding values before the current hour before sending them to the device, and only sending up to the requested timestamp.

In that case, I will not send them from Breezy Weather directly.

For your UV issue, maybe try sending an integer?

**Comment by joserebelo** [comment]
> In that case, I will not send them from Breezy Weather directly.

Do you want me to update the PR to filter them out?

> For your UV issue, maybe try sending an integer?

Need to check this, I need to review all the values for all endpoints, the Zepp OS API is weird.

**Comment by papjul** [comment]
> > In that case, I will not send them from Breezy Weather directly.
> 
> Do you want me to update the PR to filter them out?

You can use nextHourlyForecast from the Weather object, if you rebase.

Otherwise, I will do it before merging after next Gadgetbridge version is released (there are also a few things I want to adjust) ;)

**Comment by joserebelo** [comment]
> You can use nextHourlyForecast from the Weather object, if you rebase.

Done. Happy to address any other comments you might have, if you think are relevant for this PR.

**Comment by joserebelo** [comment]
And by the way - I have a branch where I was experimenting with sending multiple locations to Gadgetbridge: https://github.com/joserebelo/breezy-weather/commit/ea3acc8934d2def8eb489c3b9c169db7e1c287ab

Not relevant to this PR, just a head's up if this impacts the changes you want to adjust.

**Comment by papjul** [comment]
1) "Cached Weather Data" show "0" for daily humidity, wind speed and wind direction, do you make the difference between a 0 and a `null`? (= is it just a display error on app? maybe show "N/A" instead?)
2) We use -1 for wind direction on Breezy Weather when there is no main wind direction (usually when there is no wind or it's too low to have any direction). Is Gadgetbridge able to understand it? If not, what should be sent instead?

My changes (as you were interested): https://github.com/breezy-weather/breezy-weather/commit/1493ae7371b242c40ea298f919dc4260eff85b09

**Comment by joserebelo** [comment]
> "Cached Weather Data" show "0" for daily humidity, wind speed and wind direction, do you make the difference between a 0 and a null? (= is it just a display error on app? maybe show "N/A" instead?)

> We use -1 for wind direction on Breezy Weather when there is no main wind direction (usually when there is no wind or it's too low to have any direction). Is Gadgetbridge able to understand it? If not, what should be sent instead?

For both of these, there is currently no distinction for the new fields, as it also did not exist in the same fields for the current day, and I kept the same semantic.

However, this is something that we can handle on the Gadgetbridge side, since we are currently coalesce null values from the json payload to the expected defaults / unknown values.

So any for any unknown values, the preference would be to not send them or send them as null, and let Gadgetbridge default to "unknown".

**Pull request closed without merging**
