### PR TITLE
Rewrite XML previews of texts in English

### LINKED ISSUE #338: Rewrite XML previews of texts in English (instead of Chinese)
For better maintenance, let’s move all tools:text to English equivalent.

### PR DESCRIPTION
**Pull request by meenbeese**
Fixes #338 

- Translated all `tools:text` strings to English
- Fixed a few wording and spacing issues
- Removed some weird spaces and hyphens

Please let me know if I missed anything, there were a lot of files to go through. 😁

### CODE REVIEW

**Comment by papjul** [comment]
Thank you very much, it's useful!

However, you also changed correct English texts to wrong texts :(

Also, translated Chinese texts are rarely matching what's showing in the app. To be really useful, it would be great you open the app in parallel in English (US) and you write down real life examples (it doesn't have to be the same text as what was in Chinese, you can change it).

Thank you!

**Comment by meenbeese** [comment]
> Thank you very much, it's useful!

Thanks for reviewing, here is what I fixed from before:

> However, you also changed correct English texts to wrong texts :( Such as "[Cooling Degree Day](https://en.m.wikipedia.org/wiki/Heating_degree_day)" renamed "Cool Degree Day", inverted "France, Ain", removed space between number and unit, etc. There are also some XML files showing as entirely rewritten for some reason.

I am not entirely familiar with weather terminology, so I thought that `Cooling Degree Day` was a grammar issue, but I now fixed it. However, I still believe that `Ain, France` is the correctly was to write it by going from narrow to broader. Is there a different convention for meteorology usage? I removed extra spaces because my IDE told that that wouldn't appear anyway with the line breaks being present. Lastly, I didn't change any content in the XML files, but merely removed the excessive indentation.
 
> Also, translated Chinese texts are rarely matching what's showing in the app. To be really useful, it would be great you open the app in parallel in English (US) and you write down real life examples (it doesn't have to be the same text as what was in Chinese, you can change it).

It is not easy to know which layout is used in which part of the app, so if you have specific recommendations on what to change, I would be happy to do so. For example, I could use a Western city instead of `Qingdao`? What do you have in mind?

**Comment by papjul** [comment]
> > Thank you very much, it's useful!
> 
> Thanks for reviewing, here is what I fixed from before:
> 
> > However, you also changed correct English texts to wrong texts :( Such as "[Cooling Degree Day](https://en.m.wikipedia.org/wiki/Heating_degree_day)" renamed "Cool Degree Day", inverted "France, Ain", removed space between number and unit, etc. There are also some XML files showing as entirely rewritten for some reason.
> 
> I am not entirely familiar with weather terminology, so I thought that `Cooling Degree Day` was a grammar issue, but I now fixed it. However, I still believe that `Ain, France` is the correctly was to write it by going from narrow to broader. Is there a different convention for meteorology usage? I removed extra spaces because my IDE told that that wouldn't appear anyway with the line breaks being present. Lastly, I didn't change any content in the XML files, but merely removed the excessive indentation.
> 
> > Also, translated Chinese texts are rarely matching what's showing in the app. To be really useful, it would be great you open the app in parallel in English (US) and you write down real life examples (it doesn't have to be the same text as what was in Chinese, you can change it).
> 
> It is not easy to know which layout is used in which part of the app

Look at XML filenames, most of them are widgets followed by the name (in English) of the widget. Other are rather easy to guess using the same logic, I think. Do you use Android Studio when doing this?

> if you have specific recommendations on what to change, I would be happy to do so. For example, I could use a Western city instead of `Qingdao`?

Just use any city you like, a Canadian one will change from the usual suspects 🙂

**Comment by meenbeese** [comment]
GitHub Actions is harassing me again :/ Sorry for taking so long on this PR, I will try to wrap this up whenever I find time.

**Comment by papjul** [comment]
Don't worry, just reopen a new PR whenever you feel like it! 😊

**Pull request closed without merging**
