### PR TITLE
Add Obtainium Button To README

### PR DESCRIPTION
**Pull request by Hamster45105**
This PR adds a "Get it on Obtainium" button to the README.

The reason for having to route the link through https://github.com/intradeus/http-protocol-redirector is because markdown on GitHub does not support custom protocols (which obtanium:// is).

Prereleases are disabled by default.

### CODE REVIEW

**Comment by papjul** [comment]
Isn't it better to just paste GitHub URL in Obtainium instead of using a convoluted way with a 3rd party involved and that will fail on devices not supporting this customized protocol?

**Comment by Hamster45105** [comment]
If a user doesn't have Obtainium installed or doesn't know what it is, they probably won't click the button, so having it fail on devices without Obtainium installed shouldn't be a problem.

Also, this provides an option for users to easily add the app to Obtainium as they are looking at the project README. Additionally, the 3rd party method of routing the URL is in fact the one recommended by the Obtainium project maintainer as mentioned in: https://github.com/ImranR98/Obtainium/issues/1287#issuecomment-1909151372

**Comment by Hamster45105** [comment]
Another possibility is that I could create a simple HTML page at `/docs/redirect-obtainium.html` which would redirect the user to the custom protocol.

This would remove the 3rd party element, but would require you to enable GitHub pages for the `/docs`directory. 

However, the GitHub pages site could be used in the future to move the help .md files over to a simple help site as thought of in https://github.com/breezy-weather/breezy-weather/issues/169

**Comment by papjul** [comment]
What about having regular https links?
Taping on https://play.google.com links opens the relevant app in the Play Store app for those who have it installed and leave users without in the browser. Same thing with F-Droid links.
This is what most (if not all) Download from F-Droid/Play Store buttons do in my experience, and it looks much cleaner to me.

Unfortunately, Obtainium doesn't seem to support opening GitHub links, maybe something to suggest on their repo?

**Comment by Hamster45105** [comment]
Yes, that does make a lot more sense. It has been suggested and we will just have to see if it gets done.

**Comment by Hamster45105** [comment]
I've updated the README link with the new official Obtainium redirect page. Does that suit the project better?

**Comment by papjul** [comment]
Blank page on my side

**Comment by Hamster45105** [comment]
That's weird. Do you not see this when you click on the button?

Screenshot

Here's the link it should be taking you to: [Obtainium Redirect](https://apps.obtainium.imranr.dev/redirect?r=obtainium://app/%7B%22id%22%3A%22org.breezyweather%22%2C%22url%22%3A%22https%3A%2F%2Fgithub.com%2Fbreezy-weather%2Fbreezy-weather%22%2C%22author%22%3A%22breezy-weather%22%2C%22name%22%3A%22Breezy%20Weather%22%2C%22preferredApkIndex%22%3A0%2C%22additionalSettings%22%3A%22%7B%5C%22includePrereleases%5C%22%3Afalse%2C%5C%22fallbackToOlderReleases%5C%22%3Afalse%2C%5C%22filterReleaseTitlesByRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22filterReleaseNotesByRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22verifyLatestTag%5C%22%3Afalse%2C%5C%22dontSortReleasesList%5C%22%3Afalse%2C%5C%22useLatestAssetDateAsReleaseDate%5C%22%3Afalse%2C%5C%22trackOnly%5C%22%3Afalse%2C%5C%22versionExtractionRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22matchGroupToUse%5C%22%3A%5C%22%5C%22%2C%5C%22versionDetection%5C%22%3Atrue%2C%5C%22releaseDateAsVersion%5C%22%3Afalse%2C%5C%22useVersionCodeAsOSVersion%5C%22%3Afalse%2C%5C%22apkFilterRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22invertAPKFilter%5C%22%3Afalse%2C%5C%22autoApkFilterByArch%5C%22%3Atrue%2C%5C%22appName%5C%22%3A%5C%22%5C%22%2C%5C%22exemptFromBackgroundUpdates%5C%22%3Afalse%2C%5C%22skipUpdateNotifications%5C%22%3Afalse%2C%5C%22about%5C%22%3A%5C%22Breezy%20Weather%20is%20a%20weather%20app%20with%20a%20strong%20focus%20on%20design%2C%20with%20a%20simple%2C%20clean%20UX%2C%20smooth%20animations%2C%20and%20Material%20Design%20all%20over%2C%20plus%20lots%20of%20customizability.%5C%22%7D%22%7D)

It's working perfectly normally for me.

**Comment by papjul** [comment]
Ah yeah, it worked as soon as I enabled JavaScript. Not sure why it would need it to just show basic HTML.

**Pull request merged**
