### PR TITLE
More screenshots!

### PR DESCRIPTION
**Pull request by TheGamer1002**
Taken on Google P6P with latest GitHub release

### CODE REVIEW

**Comment by TheGamer1002** [comment]
Wow, 69th issue/PR. Nice.

**Comment by papjul** [comment]
Thank you, I didn't make newer screenshots before because I knew I wanted to make some changes.

Release v4.0.3 includes:
- Air quality data for AccuWeather
- New icons
- Some tweaking on header

As you have a bigger phone than mine that can show more info per screenshot, could you make screenshots again with latest version as a new pull request?

Please name the files: 01.png, 02.png, 03.png, 04.png and remove the older files.

Thank you!

**Comment by TheGamer1002** [comment]
Of course!

**Comment by papjul** [comment]
If you have a city with weather Partly cloudy (blue sky background with clouds), it would be even better ;)

**Comment by TheGamer1002** [comment]
> If you have a city with weather Partly cloudy (blue sky background with clouds), it would be even better ;)

Does mostly cloudy have the same effect? I'll check on satellite to see if I can find a good one.

**Comment by papjul** [comment]
No, it's good, I was asking it, because your previous pull request (this one) showed cloudy (grey tones), which is less appealing for a presentation of the app ;)

**Pull request closed without merging**
