### PR TITLE
fix: let Chinese alternative calendar use right format

### PR DESCRIPTION
**Pull request by CoelacanthusHex**
Need plus https://github.com/breezy-weather/breezy-weather/commit/9ce452a2f1a2df4434539c789ef53f0c7a8942e6 or https://github.com/breezy-weather/breezy-weather/commit/c2c454eb693e448df8699b46ff30b9c84923ca29

### CODE REVIEW

**Comment by CoelacanthusHex** [comment]
Possible solutions:
- specially treat Chinese Calendar, use "MMM d" directly.
- stop use `DateTimePatternGenerator.getBestPattern()`, write map manually.

**Comment by CoelacanthusHex** [comment]
Considering there are only a few alternative calendars, the second one may be a good choice.

**Comment by CoelacanthusHex** [comment]
I implemented the first one in https://github.com/breezy-weather/breezy-weather/commit/32d6a9f234dffd68a627b8f78068a4f0b063fa2d, if you like this way, you can merge this pr and cherry pick that commit.

**Comment by CoelacanthusHex** [comment]
I implemented the second one in https://github.com/breezy-weather/breezy-weather/commit/c2c454eb693e448df8699b46ff30b9c84923ca29, if you like this way, you can merge this pr and cherry pick that commit.

**Comment by papjul** [comment]
Implemented in d52af91605e70fd2e51d6c526b77f321845abfa0

There is now a mix of Chinese and English when we use the Chinese calendar in languages other than Chinese :/

**Pull request closed without merging**
