### PR TITLE
Proposed updates to approved strings of Chinese (Simplified)

### PR DESCRIPTION
**Pull request by cloudfish**
I noticed some of the air quality levels are strange in Chinese (Simplified), but they are read-only on weblate. I proofread these strings. Below are rationales for the modifications:

Translation for "hurricane":
No need to include two translations here. "飓风" is the standard term. ref: https://zh.wikipedia.org/zh-cn/%E8%92%B2%E7%A6%8F%E6%B0%8F%E9%A2%A8%E7%B4%9A

Translation for the air quality levels and their descriptions:
The original translation seems to come from an LLM. Although of higher quality than traditional machine translation, it is still erroneous. The translation for "Fair" is especially problematic. The original translation "有利" means "advantageous".
AccuWeather no longer provide Chinese (Simplified) version. To overcome this, you can just open Chinese (Traditional) version of the website (ref e.g. https://www.accuweather.com/zh/hk/hong-kong/1123655/air-quality-index/1123655 ) and use Google translate to convert Chinese (Traditional) air quality levels and descriptions to Chinese (Simplified). I use the conversion result unmodified except for a few words (品质 -> 质量, 水准 -> 水平) to make the wording more natural for mainland China users. These two words are also used in the original translation.

Translation for "Alert":
No need to retain translation of "level" here.

### CODE REVIEW

**Comment by papjul** [comment]
> AccuWeather no longer provide Chinese (Simplified) version.

We use "中文 (SIM)" translation that is still available to choose from the website on my side: https://www.accuweather.com/zh/settings

> The original translation seems to come from an LLM. Although of higher quality than traditional machine translation, it is still erroneous.

If there are errors, it would be best to fix them upstream

> No need to include two translations here. "飓风" is the standard term. ref: https://zh.wikipedia.org/zh-cn/%E8%92%B2%E7%A6%8F%E6%B0%8F%E9%A2%A8%E7%B4%9A

This page lists two translations for Mainland China: 飓风／台风

> Translation for "Alert":
> No need to retain translation of "level" here.

It's back to "Waiting for review" status, you can edit it even if you're not in the reviewers team.

**Comment by cloudfish** [comment]
I prefer the translation from CMA because it is a published standard.
Another standard with identical translation of the scale: https://www.cma.gov.cn/zfxxgk/gknr/flfgbz/bz/202209/P020220921550350765032.pdf

**Comment by papjul** [comment]
> I prefer the translation from CMA because it is a published standard.

I believe Wikipedia users would prefer too! Could you update it there and update the source in the Wikipedia article as well so that we are all on the same page? :) I will take care of updating translation of Breezy Weather simplified Chinese after that ;)

**Comment by cloudfish** [comment]
Done on Wikipedia.

**Pull request merged**
