### PR TITLE
Chronus icon packs - fix mapping of weather codes

### LINKED ISSUE #724: Chronus icon set mapping incorrect for some icons
### Steps to reproduce

I've been using my own Chronus icon packs with Breezy Weather and I've noticed that the icon mapping in Chronus for Thunder, Thunderstorm and Haze are off when compared to Breezy Weather.

Below is a comparison of my Google Now Chronus icon set and the default Pixel icon set in Breezy Weather. I've circled the icons which are mapped incorrectly for Chronus.

| Chronus | Breezy Weather |
| --- | --- |
| image | image

### Expected behavior

Both icon sets should use similar icons for all conditions.

### Actual behavior

The icon set mapping in Chronus is slightly off when compared to Breezy Weather. 

### Weather source used

All

### Breezy Weather version

5.0.3-alpha

### Android version

Android 14

### Device

Samsung Galaxy A53

### Other details

[Here](https://github.com/DvTonder/Sample_icon_set?tab=readme-ov-file#original-yahoo-weather-codes) is a list of the icons and what they are mapped to in Chronus. My suggestions are Thunderstorms should be mapped to code 4 and Haze mapped to code 21. I'm not sure what the Thunder icon is supposed to represent as I haven't seen it being used by any of the providers so far and Breezy uses the same icon as Thunderstorms.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.14 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

### PR DESCRIPTION
**Pull request by min7-i**
This should fix #724 by updating the mapping of the following weather codes:

| weather type | old | new |
| --- | --- | --- |
| rain | 11 (showers) | 12 (rain) |
| haze | 19 (dust) | 21 (haze) |
| sleet | 5 (mixed rain and snow) | 18 (sleet) |
| thunder | 37 (isolated thunderstorms (day))<br>47 (scattered thundershowers (night)) | 4 (thunderstorms) |
| thunderstorm (night) | 45 (scattered showers (night)) | 47 (scattered thundershowers (night)) |

### CODE REVIEW

**Comment by papjul** [comment]
5 looks correct to me for SLEET. In Breezy Weather, sleet means "mix of rain and snow" while "sleet" is a regional variant term so it's best to define it as "mix of rain and snow" directly. See https://en.m.wikipedia.org/wiki/Sleet

**Comment by min7-i** [comment]
Right. I was misled by the name of the weather code. Now I remember that we talked about it when the translation for "Rain and snow mixed" was added.

I'll wait for cloneofghosts' feedback to see if anything else comes up and then I can change it back to 5.

**Comment by cloneofghosts** [comment]
The only thing I would really change would be swapping the icons used for Thunder and Thunderstorm. From what I can tell that's the icon which Breezy Weather uses most often to represent Thunderstorm.

**Comment by papjul** [comment]
`THUNDER` code only exists with Météo-France, SMHI and OpenWeather, and refers to a specific condition in my understanding:
- `THUNDER` is a thunder condition with no rain. See https://en.wikipedia.org/wiki/Dry_thunderstorm
- `THUNDERSTORM` is thunder associated with rain and/or wind

**Comment by cloneofghosts** [comment]
Chronus doesn't have any icons to represent a thunderstorm with no rain. Would it make sense to map both of the icons to code 4 (thunderstorms) as I don't think using a day/night icon would make sense for Thunder.

**Comment by min7-i** [comment]
I tried to find some other recent Chronus icon packs to get an impression of which icons are commonly used for the mapped weather codes, but all I could find were DvTonder's icon packs where the styles haven't been updated for a while, I guess.

So could you share a screenshot of what the debug version looks like with your icon pack?

**Comment by cloneofghosts** [comment]
Here's how the icon pack looks like on the debug version

Screenshot_20240302_203041_Breezy Weather

**Comment by min7-i** [comment]
> Would it make sense to map both of the icons to code 4 (thunderstorms) as I don't think using a day/night icon would make sense for Thunder.

I might have misunderstood your question. Thunder is already mapped to 4 or are you asking to map thunderstorms to 4 as well? In that case I'd wonder why we should use a generic icon for thunderstorms when there are dedicated icons for thunderstorms at day and night.

**Comment by cloneofghosts** [comment]
I'm asking to map thunderstorms to code 4. From my experience most APIs/sites use a generic icon to represent thunderstorms and the day/night icon is used to either represent cloud cover (mostly/partly cloudy) or a chance of thunderstorms occurring.

I believe the weather providers in Chronus is mapped the same way with the generic icon used to represent thunderstorms and the day/night one used to represent the chance of thunderstorms.

**Comment by min7-i** [comment]
> [...] the day/night icon is used to either represent cloud cover (mostly/partly cloudy) or a chance of thunderstorms occurring.

My understanding is that the day/night icon is used when the thunderstorms are lighter or when it's rather a thundershower. This would at least correspond to the [icons that MET Norway](https://github.com/metno/weathericons/tree/main/weather) uses:

icons

However, as we don't distinguish between different types of thunderstorms or thundershowers, mapping thunderstorms to 4 might actually make more sense now that I think about it. So I'll go ahead and adjust this.

**Comment by min7-i** [comment]
This should be fine now.

**Comment by cloneofghosts** [comment]
Looks good to me.

**Pull request merged**
