### PR TITLE
RADAR.md: Update RainViewer free/paid features

### PR DESCRIPTION
**Pull request by Socob**
See https://play.google.com/store/apps/details?id=com.lucky_apps.RainViewer

### CODE REVIEW

**Comment by papjul** [comment]
We only recommend the website, not the app which is not FOSS, sorry

**Comment by Socob** [comment]
Sorry, I guess that was unclear. I’m only linking to the app page because I couldn’t find information about free vs. premium anywhere else. The point of this PR is to make clear that forecasts aren’t included in the free version anymore.

**Comment by papjul** [comment]
> Sorry, I guess that was unclear.

It's written below the table:

> Websites below often offer closed source apps as well, but adding a bookmark to your home screen is usually more privacy-conscious.

> The point of this PR is to make clear that forecasts aren’t included in the free version anymore.

Well-spotted! I'm closing this PR and will let you open another one to only change the forecast part? Thanks!

**Comment by Socob** [comment]
By “unclear”, I meant myself being unclear, not the page ;-)

But I’m confused now – what do you actually want changed in this PR? To not mention the paid version? I don’t actually know if it’s app-only, I just thought it didn’t make sense to list a free version without saying what the paid version is.

**Comment by papjul** [comment]
The paid version is not available on the website. The website itself is entirely free, but may miss some features only available in the app which we don't recommend, so no need to mention the app and its paid features. If forecast is no longer available on the website, the PR is to just remove that. I can do the modification myself but I wanted to let you take the credit ;)

**Comment by Socob** [comment]
OK, will do that then!

**Pull request closed without merging**
