### PR TITLE
New source: Qweather

### LINKED ISSUE #207: QWether api （和风天气api）
### Link to publicly available documentation of the API

https://dev.qweather.com/en/docs/start/

### Available and not available data

**Available**
1000request/per day

Real-time weather
Hourly forecast(24h)
Daily forecast(3-7d)
grid weather also

Minutely-Precipitation

Warning
Indices
Air Quality
Sun and Moon

**Not available**

Time Machine
Tropical Cyclone
Solar Radiation

Please note that this source is for Chinese especially, people in other countries are suggested to use Accuweather or Openweather as substitute.

### Are you going to develop yourself the new provider for the app?

Yes, I'd like to assist but need some help as a noob maybe.

### Give a bit more details or context about this source

Reasons
Accuweather allow only 50 requests per day.
Current China data api do not support Minutely-Precipitation also

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written the name of the source as the title of this issue.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)** and this source is not part of it.

### PR DESCRIPTION
**Pull request by itsHenry35**
as discussed in https://github.com/breezy-weather/breezy-weather/issues/207

Fix #207

### CODE REVIEW

**Comment by papjul** [comment]
I don't know what you did but please don't commit `app/objectbox-models/default.json.bak`. Please revert this file and stash your commits into one.

If you need help: https://github.com/breezy-weather/breezy-weather/blob/main/CONTRIBUTE.md#submit

**Comment by itsHenry35** [comment]
> I don't know what you did but please don't commit `app/objectbox-models/default.json.bak`. Please revert this file and stash your commits into one.
> 
> If you need help: https://github.com/breezy-weather/breezy-weather/blob/main/CONTRIBUTE.md#submit

seems like it's generated? after an initial build on my IDE, the file got changed

**Comment by papjul** [comment]
Yes, it is, although I don't reproduce it, otherwise my newer commits would include it. Anyway, you mustn't commit it as it is not part of this PR.

**Comment by itsHenry35** [comment]
@papjul Please see if it is all right now

**Comment by papjul** [comment]
Thank you, it's ready for my review. I will also make a migration script china > qweather to ease the transition.

**Comment by itsHenry35** [comment]
> Thank you, it's ready for my review. I will also make a migration script china > qweather to ease the transition.

After all, there is still a major issue, which is the imformal response type of qweather as i mentioned. When it fails (return http code 200 but a code parameter in json which is 404 or 403 or etc. ), the program just returns parse failed. I don't really know how to handle this elegantly.

**Comment by papjul** [comment]
Merged in a feature-branch in #574, not merging in `main` for now as review is pending to resolve some concerns

**Pull request closed without merging**
