### PR TITLE
fix: refresh lag (coroutine is better launched in io dispatcher)

### PR DESCRIPTION
**Pull request by jayyuz**
test in xiaomi11 and iqoo neo7, found lagging in refresh. reason is take too much time in RefreshHelper#getLocation (avg in 166ms, max 592ms)

### CODE REVIEW

**Comment by jayyuz** [comment]
企业微信截图_38f630af-3b03-4683-b3a0-922aaeb29383

**Comment by jayyuz** [comment]
image
running in main thread and more than  500ms

**Comment by papjul** [comment]
LGTM, thank you very much!

If you see other areas of improvements, feel free to have a look!

**Comment by jayyuz** [comment]
okk~~~

**Pull request merged**
